// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vdnkwwwmxzzkpiwsxzur.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZkbmt3d3dteHp6a3Bpd3N4enVyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg3Njc4MzEsImV4cCI6MjA2NDM0MzgzMX0.c78LAwOACiPwiO_BoQ2n1vPISsWz80iCtVABBFNf48s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);